In [1]:
import numpy as np

from sklearn.decomposition import NMF

In [2]:
R = np.array([
    [5, 3, 0, 1, 4],
    [4, 0, 0, 1, 0],
    [1, 1, 0, 5, 0],
    [0, 0, 5, 4, 0],
    [0, 3, 4, 0, 0]
])

R

array([[5, 3, 0, 1, 4],
       [4, 0, 0, 1, 0],
       [1, 1, 0, 5, 0],
       [0, 0, 5, 4, 0],
       [0, 3, 4, 0, 0]])

In [3]:
k = 4

In [4]:
model = NMF(n_components=k, init='random', random_state=42)
U = model.fit_transform(R)  
V = model.components_

print("U-matrix:")
print(U)

print("V-matrix:")
print(V)

U-matrix:
[[0.05802402 0.         0.47053255 2.36164897]
 [0.27085818 0.         0.34749831 0.        ]
 [3.86428174 0.         0.06193332 0.44326872]
 [3.16161732 2.75014089 0.         0.        ]
 [0.         2.30599696 0.         1.22115509]]
V-matrix:
[[5.16005626e-02 0.00000000e+00 1.56625664e-02 1.26336307e+00
  0.00000000e+00]
 [0.00000000e+00 2.18856055e-01 1.77305262e+00 0.00000000e+00
  0.00000000e+00]
 [1.09423850e+01 0.00000000e+00 0.00000000e+00 1.91454575e+00
  2.39596802e+00]
 [0.00000000e+00 1.45564372e+00 0.00000000e+00 8.36479764e-03
  9.24742648e-01]]


In [5]:
predicted_matrix = np.dot(U, V)

predicted_matrix

array([[5.15174233e+00, 3.43771949e+00, 9.08805135e-04, 9.93916209e-01,
        3.31129845e+00],
       [3.81643670e+00, 0.00000000e+00, 4.24233417e-03, 1.00749363e+00,
        8.32594832e-01],
       [8.77097348e-01, 6.45241326e-01, 6.05245694e-02, 5.00427286e+00,
        5.58299744e-01],
       [1.63141233e-01, 6.01884986e-01, 4.92566355e+00, 3.99427056e+00,
        0.00000000e+00],
       [0.00000000e+00, 2.28224813e+00, 4.08865394e+00, 1.02147152e-02,
        1.12925419e+00]])

In [6]:
print("ماتریس اصلی:")
print(R)
print("\nماتریس بازسازی‌شده (پیش‌بینی‌شده) با NMF:")
print(np.round(predicted_matrix, 2))

ماتریس اصلی:
[[5 3 0 1 4]
 [4 0 0 1 0]
 [1 1 0 5 0]
 [0 0 5 4 0]
 [0 3 4 0 0]]

ماتریس بازسازی‌شده (پیش‌بینی‌شده) با NMF:
[[5.15 3.44 0.   0.99 3.31]
 [3.82 0.   0.   1.01 0.83]
 [0.88 0.65 0.06 5.   0.56]
 [0.16 0.6  4.93 3.99 0.  ]
 [0.   2.28 4.09 0.01 1.13]]
